[project]
name = "obu-1c-ad"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "dotenv>=0.9.9",
    "logging>=0.4.9.6",
    "psycopg2>=2.9.10",
]
